[features]
seeds = false
skip-lint = false
[programs.localnet]
airdrop_program = "8w26X5YoBxtkz4yFyhuuVEeodNXyMqZZnvbqe666ncnW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/dexter/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
